spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ricepasta?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1248

mybatis.type-aliases-package=com.SpringWeb.RicePasta.Mapper
mybatis.mapper-locations=mybatis/**/*.xml